# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'CustomSliderFramework', :path => '.'
  # Pods for Example

end

target 'CustomSliderFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomSliderFramework

  target 'CustomSliderFrameworkTests' do
    # Pods for testing
  end

end
